'use client';

import { useEffect, useState } from 'react';

export default function StatusPage() {
    const [status, setStatus] = useState<any>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    const checkStatus = async () => {
        try {
            setLoading(true);
            const res = await fetch('/api/system/status');
            if (!res.ok) {
                // If 401, it means middleware blocked us or something else
                if (res.status === 401) {
                    throw new Error('401 Unauthorized - Middleware blocked access. Check Auth configs.');
                }
                throw new Error(`HTTP ${res.status}`);
            }
            const data = await res.json();
            setStatus(data);
        } catch (err: any) {
            setError(err.message);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        checkStatus();
    }, []);

    if (loading) return (
        <div className="p-8 font-mono text-sm text-gray-400">
            Running system diagnostics...
        </div>
    );

    if (error) return (
        <div className="p-8 font-mono text-sm text-red-500">
            <h1 className="text-xl font-bold mb-4">Diagnostics Failed</h1>
            <p>Error: {error}</p>
            <button
                onClick={checkStatus}
                className="mt-4 px-4 py-2 border border-red-500 hover:bg-red-900/20"
            >
                Retry
            </button>
        </div>
    );

    return (
        <div className="min-h-screen bg-black text-green-500 font-mono p-8 font-mono">
            <header className="mb-8 border-b border-green-900 pb-4">
                <h1 className="text-2xl font-bold text-green-400">RPCN DIAGNOSTICS</h1>
                <div className="flex gap-4 text-sm mt-2 opacity-70">
                    <span>Status: {status?.status}</span>
                    <span>Timestamp: {status?.timestamp}</span>
                    <span>Env: {status?.checks?.env?.NODE_ENV || 'unknown'}</span>
                </div>
            </header>

            <main className="grid gap-8">
                {/* Neo4j Section */}
                <section className="border border-green-900/50 p-4 rounded bg-green-900/10">
                    <h2 className="text-xl font-bold mb-4 flex items-center gap-2">
                        {status?.checks?.neo4j?.status === 'Connected' ? '✅' : '❌'} Neo4j
                    </h2>
                    <pre className="text-xs overflow-auto bg-black/50 p-2 rounded">
                        {JSON.stringify(status?.checks?.neo4j, null, 2)}
                    </pre>
                </section>

                {/* Qdrant Section */}
                <section className="border border-green-900/50 p-4 rounded bg-green-900/10">
                    <h2 className="text-xl font-bold mb-4 flex items-center gap-2">
                        {status?.checks?.qdrant?.status === 'Connected' ? '✅' : '❌'} Qdrant
                    </h2>
                    <pre className="text-xs overflow-auto bg-black/50 p-2 rounded">
                        {JSON.stringify(status?.checks?.qdrant, null, 2)}
                    </pre>
                </section>

                {/* Environment Section */}
                <section className="border border-green-900/50 p-4 rounded bg-green-900/10">
                    <h2 className="text-xl font-bold mb-4">Environment Keys</h2>
                    <ul className="grid grid-cols-2 gap-2 text-sm">
                        {Object.entries(status?.checks?.env || {}).map(([key, value]) => (
                            <li key={key} className="flex justify-between border-b border-green-900/30 pb-1">
                                <span>{key}</span>
                                <span className={value ? 'text-green-400' : 'text-red-500'}>
                                    {value ? 'PRESENT' : 'MISSING'}
                                </span>
                            </li>
                        ))}
                    </ul>
                </section>
            </main>

            <footer className="mt-8 text-center opacity-30 text-xs">
                Generated by Antigravity Agent
            </footer>
        </div>
    );
}
